/*
   Copyright (c) 2013 Broadcom Corporation
   All Rights Reserved

    <:label-BRCM:2013:DUAL/GPL:standard
    
    Unless you and Broadcom execute a separate written software license
    agreement governing use of this software, this software is licensed
    to you under the terms of the GNU General Public License version 2
    (the "GPL"), available at http://www.broadcom.com/licenses/GPLv2.php,
    with the following added to such license:
    
       As a special exception, the copyright holders of this software give
       you permission to link this software with independent modules, and
       to copy and distribute the resulting executable under terms of your
       choice, provided that you also meet, for each linked independent
       module, the terms and conditions of the license of that module.
       An independent module is a module which is not derived from this
       software.  The special exception does not apply to any modifications
       of the software.
    
    Not withstanding the above, under no circumstances may you combine
    this software in any way with any other Broadcom software provided
    under a license other than the GPL, without Broadcom's express prior
    written consent.
    
    :> 
*/

/*  File automatically generated by Reggae at 15/01/2013  09:26:08   */

/* Addresses for Multiple blocks and/or functions */

#include "rdp_ubus.h"

uint32_t UBUS_UBUS_MASTER_BRDG_REG_EN_ARRAY [ 3 ] =
{
	UBUS_UBUS_MASTER_0_BRDG_REG_EN_ADDRESS,
	UBUS_UBUS_MASTER_1_BRDG_REG_EN_ADDRESS,
	UBUS_UBUS_MASTER_2_BRDG_REG_EN_ADDRESS
} ;

EXPORT_SYMBOL(UBUS_UBUS_MASTER_BRDG_REG_EN_ARRAY);

uint32_t UBUS_UBUS_MASTER_BRDG_REG_REQ_CNTRL_ARRAY [ 3 ] =
{
	UBUS_UBUS_MASTER_0_BRDG_REG_REQ_CNTRL_ADDRESS,
	UBUS_UBUS_MASTER_1_BRDG_REG_REQ_CNTRL_ADDRESS,
	UBUS_UBUS_MASTER_2_BRDG_REG_REQ_CNTRL_ADDRESS
} ;

EXPORT_SYMBOL(UBUS_UBUS_MASTER_BRDG_REG_REQ_CNTRL_ARRAY);

uint32_t UBUS_UBUS_MASTER_BRDG_REG_HYST_CTRL_ARRAY [ 3 ] =
{
	UBUS_UBUS_MASTER_0_BRDG_REG_HYST_CTRL_ADDRESS,
	UBUS_UBUS_MASTER_1_BRDG_REG_HYST_CTRL_ADDRESS,
	UBUS_UBUS_MASTER_2_BRDG_REG_HYST_CTRL_ADDRESS
} ;

EXPORT_SYMBOL(UBUS_UBUS_MASTER_BRDG_REG_HYST_CTRL_ARRAY);

uint32_t UBUS_UBUS_MASTER_BRDG_REG_HP_ARRAY [ 3 ] =
{
	UBUS_UBUS_MASTER_0_BRDG_REG_HP_ADDRESS,
	UBUS_UBUS_MASTER_1_BRDG_REG_HP_ADDRESS,
	UBUS_UBUS_MASTER_2_BRDG_REG_HP_ADDRESS
} ;

EXPORT_SYMBOL(UBUS_UBUS_MASTER_BRDG_REG_HP_ARRAY);

uint32_t UBUS_UBUS_MASTER_BRDG_REG_REPLY_ADD_ARRAY [ 3 ] =
{
	UBUS_UBUS_MASTER_0_BRDG_REG_REPLY_ADD_ADDRESS,
	UBUS_UBUS_MASTER_1_BRDG_REG_REPLY_ADD_ADDRESS,
	UBUS_UBUS_MASTER_2_BRDG_REG_REPLY_ADD_ADDRESS
} ;

EXPORT_SYMBOL(UBUS_UBUS_MASTER_BRDG_REG_REPLY_ADD_ARRAY);

uint32_t UBUS_UBUS_MASTER_BRDG_REG_REPLY_DATA_ARRAY [ 3 ] =
{
	UBUS_UBUS_MASTER_0_BRDG_REG_REPLY_DATA_ADDRESS,
	UBUS_UBUS_MASTER_1_BRDG_REG_REPLY_DATA_ADDRESS,
	UBUS_UBUS_MASTER_2_BRDG_REG_REPLY_DATA_ADDRESS
} ;

EXPORT_SYMBOL(UBUS_UBUS_MASTER_BRDG_REG_REPLY_DATA_ARRAY);
