#
# - Find LIBUCI
# Find the native LIBUCI includes and library
#
#  UCI_INCLUDE_DIRS - where to find uloop.h, etc.
#  UCI_LIBRARIES    - List of libraries when using UCI.
#  UCI_FOUND        - True if UCI found.


IF (LIBUCI_INCLUDE_DIRS)
  # Already in cache, be silent
  SET(LIBUCI_FIND_QUIETLY TRUE)
ENDIF (LIBUCI_INCLUDE_DIRS)

FIND_PATH(LIBUCI_INCLUDE_DIR uci.h PATH_SUFFIXES libuci)
SET(LIBUCI_NAMES uci)
FIND_LIBRARY(LIBUCI_LIBRARY NAMES ${LIBUCI_NAMES} )

# handle the QUIETLY and REQUIRED arguments and set LIBUCI_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBUCI DEFAULT_MSG LIBUCI_LIBRARY LIBUCI_INCLUDE_DIR)

IF(LIBUCI_FOUND)
  SET( LIBUCI_LIBRARIES ${LIBUCI_LIBRARY} )
  SET( LIBUCI_INCLUDE_DIRS ${LIBUCI_INCLUDE_DIR} )
ELSE(LIBUCI_FOUND)
  SET( LIBUCI_LIBRARIES )
  SET( LIBUCI_INCLUDE_DIRS )
ENDIF(LIBUCI_FOUND)

MARK_AS_ADVANCED( LIBUCI_LIBRARIES LIBUCI_INCLUDE_DIRS)
