IF (LIBNFNETLINK_INCLUDE_DIRS)
  # Already in cache, be silent
  SET(LIBNFNETLINK_FIND_QUIETLY TRUE)
ENDIF (LIBNFNETLINK_INCLUDE_DIRS)

FIND_PATH(LIBNFNETLINK_INCLUDE_DIR libnfnetlink.h PATH_SUFFIXES libnfnetlink)

SET(LIBNFNETLINK_NAMES nfnetlink)
FIND_LIBRARY(LIBNFNETLINK_LIBRARY NAMES ${LIBNFNETLINK_NAMES} )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBNFNETLINK DEFAULT_MSG LIBNFNETLINK_LIBRARY LIBNFNETLINK_INCLUDE_DIR)

IF(LIBNFNETLINK_FOUND)
  SET( LIBNFNETLINK_LIBRARIES ${LIBNFNETLINK_LIBRARY} )
  SET (LIBNFNETLINK_INCLUDE_DIRS ${LIBNFNETLINK_INCLUDE_DIR} )
ELSE(LIBNFNETLINK_FOUND)
  SET( LIBNFNETLINK_LIBRARIES )
  SET (LIBNFNETLINK_INCLUDE_DIRS )
ENDIF(LIBNFNETLINK_FOUND)

MARK_AS_ADVANCED( LIBNFNETLINK_LIBRARIES LIBNFNETLINK_INCLUDE_DIRS)
